### ISSUE TITLE
建议字幕搜索换成 字幕库

### ISSUE THREAD

**Issue by rong2er** [tofuliang/Sub-shortcut-for-RARBG#1]
http://www.zimuku.net/  我已经手动换了，不过可能脚本自动更新后又要变，SUBHD网站打开太慢，字幕库秒开

**Comment by tofuliang** [comment]
@hexianfu 建议自己实现一个并提交到 greasyfork 毕竟这个名字叫 Subhd-shortcut-for-RARBG.
